version: '3'

services:
  # backend-app:
  #   container_name: transferencias-back
  #   build:
  #     context: ./transferencias
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - appnet

  ui:
    container_name: transferencias-front
    build:
      context: ./ui-app
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    networks: 
      - appnet

networks:
  appnet:
    driver: "bridge"